CREATE TABLE `product` (
	`PROD_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`PROD_NAME` VARCHAR(255) NULL DEFAULT NULL,
	`PROD_VENDOR` VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (`PROD_ID`)
)
COLLATE='utf8mb4_0900_ai_ci' ENGINE=InnoDB AUTO_INCREMENT=3;


CREATE TABLE `product_details` (
	`PROD_DET_ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`PROD_DESC` VARCHAR(255) NULL DEFAULT NULL,
	`PROD_NAME` VARCHAR(255) NULL DEFAULT NULL,
	`PROD_PRICE` FLOAT NULL DEFAULT NULL,
	PRIMARY KEY (`PROD_DET_ID`)
)
COLLATE='utf8mb4_0900_ai_ci' ENGINE=InnoDB AUTO_INCREMENT=3;
